include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    argument_type_not_assignable: error
    invalid_assignment: ignore
    unused_local_variable: error

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false
    
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false
    always_use_package_imports: false
    require_trailing_commas: false
    avoid_dynamic_calls: false


    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: false

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    prefer_double_quotes: false
    directives_ordering: false
    #undefined_getter: false
    #argument_type_not_assignable: false
    type_annotate_public_apis: false
    avoid_void_async: false
    prefer_null_aware_operators: true
    avoid_positional_boolean_parameters: false

    # Good packages document everything
    public_member_api_docs: false
    
    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: false
  
    # Back to the 80s
    lines_longer_than_80_chars: true
    # Reglas para evitar redundancias o malas prácticas comunes
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    unnecessary_new: true